ARG ROS_DISTRO=humble
 
FROM dustynv/nano_llm:${ROS_DISTRO}-r36.3.0 as base
ENV ROS_DISTRO=${ROS_DISTRO}
SHELL ["/bin/bash", "-c"]

RUN set -euo pipefail
ENV DEBIAN_FRONTEND=noninteractive

# Get Ubuntu packages
RUN pip install --upgrade  pyaudio==0.2.12
RUN pip install nvidia-riva-client==2.17.0

FROM base AS overlay
 
RUN mkdir -p /root/ws
COPY ./src/command_listener /root/ws/src/command_listener
WORKDIR /root/ws/src
 
WORKDIR /root/ws
RUN source /opt/ros/install/setup.bash \
 && apt-get update -y \
 && rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y \
 && colcon build --symlink-install

COPY ./entrypoint.sh /
RUN chmod +x  /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["bash"]
